### ISSUE TITLE
Naming collision with `vbmc`

### ISSUE THREAD

**Issue by codekow** [kurokobo/virtualbmc-for-vsphere#9]
While this isn't a show stopper for my uses. I think it could impact or even confuse other people.

Is there a reason you named the cli `vbmc` which conflicts with [another project](https://github.com/openstack/virtualbmc)?

What if you named it `vcbmc` and `vcbmcd` (vCenter BMC) ... or `vsbmc` (yes, those names may be awful, but you get the idea)? Thoughts?

**Comment by kurokobo** [comment]
Thanks for creating issue.
It's one of the things that I thought might be a problem someday.

This project started as a "fork" of the original VirtualBMC from OpenStack, so to be precise, I didn't "give" it the same name, but I "leave" the name without giving new one.

Since this was a personal project and I wasn't using KVM, I didn't have to worry about name conflicts. And I figured I could coexist if I use both in separated containers.

In the first place, since it is a "Virtualized BMC", I think the abbreviations "VirtualBMC" and "vbmc" are very good name. The "vSphere BMC" is also attractive for my project, but difficult to use because its abbrevation "vbmc" is as same as original one...

**Comment by codekow** [comment]
Thanks for explaining the background. That makes sense.

The full name would avoid confusion for sure. What are your thoughts about something shorter like`vsbmc`? That would keep it short but would still be different? 

I'm asking in case someone finds a reason to rename it :)... I figured it was worth getting the conversation out there for any other lurkers out there using it.

**Comment by kurokobo** [comment]
Released as 0.1.0. Thanks for your contribution!

**Comment by codekow** [comment]
Great work :+1:
